apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zt4wnomwn-python 
  janus-idp.io/tekton: zt4wnomwn-python
  backstage.io/kubernetes-id: zt4wnomwn-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zt4wnomwn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml